### ISSUE TITLE
Maintenence

### ISSUE THREAD

**Issue by l1npengtul** [l1npengtul/libuvc-rs#23]
Hello, I am willing to take over maintaining this crate.

**Comment by mulimoen** [comment]
Hi @l1npengtul, thanks for your interest. Seems like you have a cool project going with [nokhwa](https://github.com/l1npengtul/nokhwa)! How would you prefer the transfer? Would you like it transferred to yourself, or should you start an organisation?

**Comment by l1npengtul** [comment]
Either works fine, I don't mind.

Thank you for the intrest in `nokhwa`!
I'm currently using it as a backend and it is in my intrest that this crate continue to be maintained. I'm currently writing a feature to add polling frames to the StreamHandle.

**Comment by mulimoen** [comment]
The approach I used for the `StreamHandle` is a bit unwieldy, I never got to changing this so one could change parameters on the camera, developments here are much needed, and I am happy to pass the torch on to see this happen.

**Comment by mulimoen** [comment]
To transfer the repository, your fork at `l1npengtul/libuvc-rs` needs to be deleted

**Comment by l1npengtul** [comment]
I plan on consolidating the device, streamh, etc. and using a singleton for the Context. If you take a look at the `nokhwa` source (note: not built due to errors) it needs ouroboros and is generally unweildy to use. Consolidating should make it in line with other crates such as V4L.

**Comment by l1npengtul** [comment]
Ok will do

**Comment by l1npengtul** [comment]
Deleted my fork.

**Comment by mulimoen** [comment]
Hope you got the invites from `crates.io` so you can publish on there too

**Comment by l1npengtul** [comment]
I did, thank you!

**Comment by l1npengtul** [comment]
I'll proceed to close this now. Thank you!

My current priority is getting AVFoundation support in `nokhwa`, but after that I will definatly come back to more activly maintain `uvc`

**Comment by mulimoen** [comment]
Thank you so much for adopting it!
