### ISSUE TITLE
cargo build failed

### ISSUE THREAD

**Issue by fly2moon2** [l1npengtul/libuvc-rs#27]
Hi,

I tried to build from my Monterey MacBook.  The cargo build failed with the following trace.  Appreciate for any suggestions.  Thanks a lot!

   Compiling uvc v0.2.0 (/Users/jack/dev/spaces/ruspaces/gitz/gitzlib/camera/libuvc)
error[E0425]: cannot find function `uvc_mjpeg2rgb` in this scope
  --> src/frame.rs:39:39
   |
39 |                 FrameFormat::MJPEG => uvc_mjpeg2rgb(self.frame.as_ptr(), new_frame.frame.as_ptr()),
   |                                       ^^^^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `uvc` due to previous error

**Comment by l1npengtul** [comment]
uvc is broken due to a lifetime error, and so is gstreamer. I recommend using avfoundation.
