### ISSUE TITLE
Vendor libuvc

### ISSUE THREAD

**Issue by leo60228** [l1npengtul/libuvc-rs#4]
Many systems do not have libuvc available, including docs.rs builders. Note that you should add it as a submodule instead of fetching the source in build.rs, as docs.rs stopped allowing network access a few months ago.

**Comment by leo60228** [comment]
You can use the [cc](https://docs.rs/cc) crate for this.

**Comment by mulimoen** [comment]
Great idea! I'll try to experiment a bit to find a good way forwards. Seems the most common approach is to introduce another crate which builds and makes the dependency visible to the linker

**Comment by mulimoen** [comment]
Which kind of assumptions could I make on the availability of `libusb`?

**Comment by leo60228** [comment]
libusb is pretty popular, but I'd say it's preferable to vendor it as well.

**Comment by leo60228** [comment]
If you can't find a good way to do that, I'd say getting it from the system would be fine, though.
