### ISSUE TITLE
ctx.devices() panics at end of device list

### ISSUE THREAD

**Issue by warner** [l1npengtul/libuvc-rs#8]
A small test program:

```rust
fn main() {
    // Get a libuvc context
    let ctx = uvc::Context::new().expect("Could not get context");

    for dev in ctx.devices().expect("Could not enumerate devices") {
        let desc = dev.description().expect("could not get description");
        println!("device [{}.{}] id=({:04x}/{:04x}): {}", dev.bus_number(), dev.device_address(),
                 desc.vendor_id, desc.product_id,
                 desc.product.unwrap_or("<unknown>".to_string()));
    }
}
```

shows me the camera device I expected, but then panics before it gets out of the loop:

```
device [20.23] id=(0bda/58bb): FULL HD 1080P Webcam
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/warner/stuff/rust/libuvc-rs/src/device.rs:78:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It's happening in the `unwrap` here:

```rust
impl<'a> Device<'a> {
    pub(crate) unsafe fn from_raw(dev: *mut uvc_device) -> Self {
        Device {
            dev: NonNull::new(dev).unwrap(),
            _dev: PhantomData,
        }
    }
```

Is the C code maybe returning a list of pointers, and using NULL to indicate the end of the list? I don't know how to read the unsafe code (I'm still pretty new at rust). I'm looking at `DeviceList` and it's `Iterator`.. am I correct in thinking that the `DeviceList` can only be iterated once? It looks like the `reached_end` state flag lives in the `DeviceList`, rather than the iterator. Would it be possible for `ctx.devices()` to build the `Device` structs right away, and store them in a regular `Vec`, rather than constructing those structs during iteration?

thanks,
 -Brian

**Comment by mulimoen** [comment]
The C code does return a null-terminated list. DeviceList can only be iterated once, the operatron to create the iterator is very cheap on the C side. I've tried to make this library allocation free, to get a list of devices you can always `.collect()` into a vector.

**Comment by mulimoen** [comment]
You should be able to pull the fixes from `crates.io`!

**Comment by warner** [comment]
that worked, thanks!
